version: "2"

services:
   apache:
     build: docker-files
     ports:
       - "${HTTPS_PORT}:443"
       - "${HTTP_PORT}:80"
     expose:
       - "80"
       - "443"
     restart: always
     volumes:
         - ./application:/var/www
         - ./docker-files/override.ini:/etc/php/7.4/apache2/conf.d/php.ini
         - ./.logs:/var/log/apache2
         - ./docker-files/certs/server.crt:/etc/ssl/certs/server.crt
         - ./docker-files/certs/server.key:/etc/ssl/private/server.key
         - ./docker-files/certs/server-chain-file.crt:/etc/ssl/certs/server-chain-file.crt
     links:
       - db:db
   db:
     image: mariadb:10.3
     restart: always
     volumes:
       - ./.db:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     ports:
       - "3390:3306"
   adminer:
     image: adminer
     ports:
       - "${ADMINER_PORT}:8080"
     links:
       - db:db
