version: "2"

services:
   apache:
     build: docker-files
     ports:
       - "8443:443"
       - "8098:80"
     expose:
       - "80"
       - "443"
     restart: always
     volumes:
         - ./application:/var/www
         - ./docker-files/override.ini:/etc/php/7.2/apache2/conf.d/php.ini
     links:
       - db:db
   db:
     image: mariadb:10.3
     restart: always
     volumes:
       - ./.db:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     ports:
       - "3398:3306"
   adminer:
     image: adminer
     ports:
       - "8096:8080"
     links:
       - db:db
